namespace DR2OTR_Randomizer
{
    partial class Form1
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.TreeNode treeNode1 = new System.Windows.Forms.TreeNode("Node6");
            System.Windows.Forms.TreeNode treeNode2 = new System.Windows.Forms.TreeNode("Node7");
            System.Windows.Forms.TreeNode treeNode3 = new System.Windows.Forms.TreeNode("Node8");
            System.Windows.Forms.TreeNode treeNode4 = new System.Windows.Forms.TreeNode("Node0", new System.Windows.Forms.TreeNode[] {
            treeNode1,
            treeNode2,
            treeNode3});
            System.Windows.Forms.TreeNode treeNode5 = new System.Windows.Forms.TreeNode("Node9");
            System.Windows.Forms.TreeNode treeNode6 = new System.Windows.Forms.TreeNode("Node10");
            System.Windows.Forms.TreeNode treeNode7 = new System.Windows.Forms.TreeNode("Node11");
            System.Windows.Forms.TreeNode treeNode8 = new System.Windows.Forms.TreeNode("Node1", new System.Windows.Forms.TreeNode[] {
            treeNode5,
            treeNode6,
            treeNode7});
            System.Windows.Forms.TreeNode treeNode9 = new System.Windows.Forms.TreeNode("Node12");
            System.Windows.Forms.TreeNode treeNode10 = new System.Windows.Forms.TreeNode("Node13");
            System.Windows.Forms.TreeNode treeNode11 = new System.Windows.Forms.TreeNode("Node14");
            System.Windows.Forms.TreeNode treeNode12 = new System.Windows.Forms.TreeNode("Node2", new System.Windows.Forms.TreeNode[] {
            treeNode9,
            treeNode10,
            treeNode11});
            System.Windows.Forms.TreeNode treeNode13 = new System.Windows.Forms.TreeNode("Node17");
            System.Windows.Forms.TreeNode treeNode14 = new System.Windows.Forms.TreeNode("Node3", new System.Windows.Forms.TreeNode[] {
            treeNode13});
            System.Windows.Forms.TreeNode treeNode15 = new System.Windows.Forms.TreeNode("Node15");
            System.Windows.Forms.TreeNode treeNode16 = new System.Windows.Forms.TreeNode("Node16");
            System.Windows.Forms.TreeNode treeNode17 = new System.Windows.Forms.TreeNode("Node4", new System.Windows.Forms.TreeNode[] {
            treeNode15,
            treeNode16});
            System.Windows.Forms.TreeNode treeNode18 = new System.Windows.Forms.TreeNode("Node5");
            this.clb_ItemList = new System.Windows.Forms.CheckedListBox();
            this.tv_Items = new System.Windows.Forms.TreeView();
            this.SuspendLayout();
            // 
            // clb_ItemList
            // 
            this.clb_ItemList.BackColor = System.Drawing.SystemColors.WindowFrame;
            this.clb_ItemList.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.clb_ItemList.CheckOnClick = true;
            this.clb_ItemList.FormattingEnabled = true;
            this.clb_ItemList.HorizontalScrollbar = true;
            this.clb_ItemList.Items.AddRange(new object[] {
            "\"MercenaryBike\"",
            "\"TIRBike\"",
            "\"GirlsBike\"",
            "\"BazookaBike\"",
            "\"RabbitBike\"",
            "\"ChopperBikeSingle\"",
            "\"ChainsawBike\"",
            "\"SuperBike\"",
            "\"Bucket\"",
            "\"Skateboard\"",
            "\"FlameThrower\"",
            "\"AirHorn\"",
            "\"TIRBikeGreenUF\"",
            "\"UltimateFanBike\"",
            "\"PushBroom\"",
            "\"PlasticBin\"",
            "\"TwoByFour\"",
            "\"GoblinMask\"",
            "\"Defibrillator\"",
            "\"CardboardBox\"",
            "\"Pallet\"",
            "\"SteelShelving\"",
            "\"HawaiianShirt1shortsDispenser\"",
            "\"FireExtinguisher\"",
            "\"NoveltyCellPhone\"",
            "\"Ketchup\"",
            "\"AmericanShowmanHelmetDispenser\"",
            "\"Dolly\"",
            "\"Coffeepot\"",
            "\"AmericanShowmanHelmetDispenser\"",
            "\"Plates\"",
            "\"GarbageBag\"",
            "\"Chair_9\"",
            "\"GarbageCan_4\"",
            "\"Brick\"",
            "\"Pylon\"",
            "\"Scissors\"",
            "\"ShowerHead\"",
            "\"MedicalTray\"",
            "\"VelvetPole\"",
            "\"FireAxe\"",
            "\"BikeEngine\"",
            "\"VacuumCleaner\"",
            "\"PottedPlant_4\"",
            "\"WaterCooler\"",
            "\"SmallSuitcase\"",
            "\"LeadPipe\"",
            "\"PropaneTank\"",
            "\"HandGun\"",
            "\"M249Bike\"",
            "\"MercAssaultRifle\"",
            "\"SixShooter\"",
            "\"HangmanGun\"",
            "\"LeafBlower\"",
            "\"WheelchairBike\"",
            "\"MinigameSniper\"",
            "\"MilitiaSniperRifle\"",
            "\"EnhancedM249\"",
            "\"SawBlade\"",
            "\"EnhancedM16\"",
            "\"Shotgun\"",
            "\"M16\"",
            "\"M249\"",
            "\"EnhancedMAR\"",
            "\"WaterGun\"",
            "\"Barrett50Caliber\"",
            "\"ZombieMask\"",
            "\"PitchForkShotgun\"",
            "\"ChuckColouredHairBlueDispenser\"",
            "\"DrinkCocktail\"",
            "\"TeddyBearSentryGun\"",
            "\"WheelPawn\"",
            "\"ChuckColouredHairGreyDispenser\"",
            "\"HotDog\"",
            "\"SpitballGun\"",
            "\"FireSpitter\"",
            "\"BFG\"",
            "\"SBFG\"",
            "\"SnowballCannon\"",
            "\"Hamburger\"",
            "\"LaserGun\"",
            "\"LightningGun\"",
            "\"RayGun\"",
            "\"TennisBallLauncher\"",
            "\"SawLauncher\"",
            "\"MoltenCannon\"",
            "\"ProtomanBlaster\"",
            "\"Theremin\"",
            "\"FountainLizard\"",
            "\"MagicianSword\"",
            "\"LongStick\"",
            "\"BigDrillMotor\"",
            "\"RotatingDisplay\"",
            "\"Auger\"",
            "\"Driller\"",
            "\"WingManJar\"",
            "\"ElectricRake\"",
            "\"Spraypaint\"",
            "\"AluminumTennisRacket\"",
            "\"AlienProbe\"",
            "\"Vodka\"",
            "\"Steak\"",
            "\"ProtomanShield\"",
            "\"ProtomanBlasterAndShield\"",
            "\"Thor\"",
            "\"LaserEyes\"",
            "\"SpaceHammer\"",
            "\"Mole\"",
            "\"Wormhole\"",
            "\"RepulseJuice\"",
            "\"SpaceWorm\"",
            "\"GasCanister\"",
            "\"HandleBar\"",
            "\"Knife\"",
            "\"FrankStandee\"",
            "\"ChuckStandee\"",
            "\"FiremanFireAxe\"",
            "\"PsychoMachete\"",
            "\"PsychoMeatCleaver\"",
            "\"PsychoMiningPick\"",
            "\"Combo_BucketDrill\"",
            "\"CroupierStick\"",
            "\"Lance\"",
            "\"Pan_heat\"",
            "\"CementSaw_combo\"",
            "\"PlateLauncherPlate\"",
            "\"BowandArrow\"",
            "\"BowandArrow_explosive\"",
            "\"BaseballBat_Metal\"",
            "\"FlamingAces\"",
            "\"GolfClub\"",
            "\"VinylRecords\"",
            "\"MusicDiscs\"",
            "\"PlateLauncher\"",
            "\"SGBallLauncherBlue\"",
            "\"FireworksBazooka_reward\"",
            "\"ZombieThrower\"",
            "\"MascotMurderballLauncher\"",
            "\"DonkeyLamp\"",
            "\"SuperMassager\"",
            "\"SpaceballBat\"",
            "\"CannedDrinks\"",
            "\"HandiChipper\"",
            "\"ElectrocutionChair\"",
            "\"FloorBuffer\"",
            "\"ZapShine\"",
            "\"UtilityCart\"",
            "\"PowerGuitar\"",
            "\"Chainsaw\"",
            "\"GiantPinkChainsaw\"",
            "\"LaserLightSword\"",
            "\"HeliBlade\"",
            "\"FlamingGloves\"",
            "\"SC37_ShoppingBoxes\"",
            "\"ComedyTrophy\"",
            "\"CementSaw\"",
            "\"NinjaKatanaSword\"",
            "\"NinjaBroadSword\"",
            "\"NinjaSword\"",
            "\"KatanaSword\"",
            "\"WackyHammer\"",
            "\"BeerHat\"",
            "\"KnifeGloves\"",
            "\"ServbotMask\"",
            "\"GiantStuffedBull\"",
            "\"Reaper\"",
            "\"Shocker\"",
            "\"ElectricProd\"",
            "\"LibertyTorch\"",
            "\"PowerExsanguinator\"",
            "\"SpikedSwordAndShield\"",
            "\"FlamingSwordAndShield\"",
            "\"poleweapon\"",
            "\"gemblower\"",
            "\"mmagloves_spiked\"",
            "\"midlengthtshirtjeansdispenser\"",
            "\"defiler\"",
            "\"battleaxe\"",
            "\"lobster\"",
            "\"plaidsuitbrownshirttiedispenser\"",
            "\"BurningSkull\"",
            "\"Basketball\"",
            "\"Zombrex\"",
            "\"KCMooseHead\"",
            "\"SpikedBat\"",
            "\"SuperSlicer\"",
            "\"ParaBlower\"",
            "\"SpeakerWeapon\"",
            "\"ElectricThunder\"",
            "\"Combo_Paddlesaw\"",
            "\"MolotovBottle\"",
            "\"FortuneTshirt1BlueJeansDispenser\"",
            "\"FreezerBomb\"",
            "\"ATMHacker\"",
            "\"BeachBall\"",
            "\"ZombieThrowerSpear\"",
            "\"NoveltyBeerMug\"",
            "\"TikiMask\"",
            "\"TreasureChest\"",
            "\"MilitaryCrate\"",
            "\"HeadStatue\"",
            "\"Shovel\"",
            "\"Sickle\"",
            "\"KidsSuperHeroEyeMaskDispenser\"",
            "\"PortableLawnMower\"",
            "\"PowerDrill\"",
            "\"Drum\"",
            "\"WilliametteMallSecurityDispenser\"",
            "\"BowlingBall\"",
            "\"NakedOutfitDispenser\"",
            "\"ArthurOutfitDispenser\"",
            "\"TIR_ChampionDispenser\"",
            "\"SwatHelmetDispenser\"",
            "\"RussianHatDispenser\"",
            "\"ShowGirlHeadPieceDispenser\"",
            "\"FlowerHeadPieceDispenser\"",
            "\"BaldNoHairDispenser\"",
            "\"MohawkHairDispenser\"",
            "\"WildFrontierHatDispenser\"",
            "\"ChuckColouredHairPinkDispenser\"",
            "\"FedoraDispenser\"",
            "\"BaseballCapTIRDispenser\"",
            "\"LadiesHatDispenser\"",
            "\"DealerVisorDispenser\"",
            "\"BaseballCapSportDispenser\"",
            "\"TuqueDispenser\"",
            "\"TennisHeadBandDispenser\"",
            "\"FunnyMaskServbotDispenser\"",
            "\"WhiteCowboyHatDispenser\"",
            "\"BlackCowboyHatDispenser\"",
            "\"FunnyMaskZombieDispenser\"",
            "\"FootballHelmetDispenser\"",
            "\"TouristBoatHatDispenser\"",
            "\"FunnyMaskLizardDispenser\"",
            "\"FunnyMaskBlankaDispenser\"",
            "\"BlackRimmedGlassesDispenser\"",
            "\"YellowTintedGlassesDispenser\"",
            "\"DarkAviatorGlassesDispenser\"",
            "\"NoveltyGlassesDispenser\"",
            "\"BlueOysterBikerOutfitDispenser\"",
            "\"SportGlassesDispenser\"",
            "\"HygieneMaskDispenser\"",
            "\"ArmyJacketPantsDispenser\"",
            "\"LargeRhinestoneGlassesDispenser\"",
            "\"YellowTrackSuitDispenser\"",
            "\"HipHopOutfitDispenser\"",
            "\"FootballUniformDispenser\"",
            "\"BaseballUniformDispenser\"",
            "\"BasketballUniformDispenser\"",
            "\"SWATOutfitDispenser\"",
            "\"BlackTuxedoBowTieDispenser\"",
            "\"SportyTrackSuitDispenser\"",
            "\"OnePiecePajamaDispenser\"",
            "\"TubeTopMiniSkirtDispenser\"",
            "\"PoolBall\"",
            "\"FishNetshirtwhitepantsDispenser\"",
            "\"CoconutBraHolaDressDispenser\"",
            "\"KnottedTopCutoffsDispenser\"",
            "\"BananaHammockDispenser\"",
            "\"SummerDressDispenser\"",
            "\"HockeyStick\"",
            "\"TatteredClothesDispenser\"",
            "\"ChuckyOutfitDispenser\"",
            "\"KidsSuperHeroCostumeDispenser\"",
            "\"TennisOutfitDispenser\"",
            "\"HawaiianShirt3PantsDispenser\"",
            "\"HawaiianShirt4PantsDispenser\"",
            "\"HawaiianShirt2shortsDispenser\"",
            "\"DealerOutfitDispenser\"",
            "\"WhiteCowboyOutfitDispenser\"",
            "\"BlackCowboyOutfitDispenser\"",
            "\"WhiteLeisureSuitDispenser\"",
            "\"SurfWetsuitDispenser\"",
            "\"CardiganSlacksDispenser\"",
            "\"CleatsDispenser\"",
            "\"AmericanShowmanOutfitDispenser\"",
            "\"ComedianOutfitDispenser\"",
            "\"PoloShirtBlueJeansDispenser\"",
            "\"HailMary\"",
            "\"FortuneTshirt2BlackJeansDispenser\"",
            "\"BobsToy\"",
            "\"SkaterOutfitDispenser\"",
            "\"TeslaBall\"",
            "\"TanJacketSlacksTurtleneckDispenser\"",
            "\"BareFeetChuckDispenser\"",
            "\"YellowSneakersDispenser\"",
            "\"BasketballHighTopsDispenser\"",
            "\"BlackCanvasSneakersDispenser\"",
            "\"WhiteLowheelsDispenser\"",
            "\"HookerBootsDispenser\"",
            "\"SandalsWhiteSocksDispenser\"",
            "\"KidsSuperHeroBootsDispenser\"",
            "\"BunnySlippersDispenser\"",
            "\"FlipFlopsDispenser\"",
            "\"BlackMilitaryBootsDispenser\"",
            "\"BlackDressShoesDispenser\"",
            "\"WhiteCowboyBootsDispenser\"",
            "\"BlackCowboyBootsDispenser\"",
            "\"WhiteTennisShoesSocksDispenser\"",
            "\"TIRWrestlingOutfit\"",
            "\"SexySpaceGirlDispenser\"",
            "\"ProtomanDispenser\"",
            "\"AlienOutfitDispenser\"",
            "\"SexySpaceGirlBoots\"",
            "\"SexySpaceGirlHair\"",
            "\"SexySpaceGirlBody\"",
            "\"AlienMask\"",
            "\"AlienSuit\"",
            "\"AlienBoots\"",
            "\"ProtomanBoots\"",
            "\"SpaceSuitBody\"",
            "\"SpaceSuitBoots\"",
            "\"SpaceSuitHelmet\"",
            "\"NinjaOutfit\"",
            "\"SportFanOutfit\"",
            "\"SoldierOutfit\"",
            "\"PsychopathOutfit\"",
            "\"NinjaFaceWearDispenser\"",
            "\"NinjaFeetDispenser\"",
            "\"NinjaHeadwearDispenser\"",
            "\"NinjaChestDispenser\"",
            "\"SoldierFacewearDispenser\"",
            "\"SoldierHeadwearDispenser\"",
            "\"SoldierFeetDispenser\"",
            "\"SoldierChestDispenser\"",
            "\"SportFanFacewearDispenser\"",
            "\"SportFanHeadwearDispenser\"",
            "\"SportFanFeetDispenser\"",
            "\"SportFanChestDispenser\"",
            "\"PsychopathFacewearDispenser\"",
            "\"PsychopathHeadwearDispenser\"",
            "\"PsychopathFeetDispenser\"",
            "\"PsychopathChestDispenser\"",
            "\"ProtomanHelmet\"",
            "\"ProtomanBody\"",
            "\"DLC_Fireman_Face\"",
            "\"DLC_Fireman_Chest\"",
            "\"DLC_Fireman_Head\"",
            "\"DLC_Cyborg_Chest\"",
            "\"DLC_Fireman_Feet\"",
            "\"DLC_Cyborg_Face\"",
            "\"DLC_Cyborg_Feet\"",
            "\"DLC_Cyborg_Head\"",
            "\"DLC_BBQChef_Chest\"",
            "\"DLC_BBQChef_Face\"",
            "\"DLC_BBQChef_Feet\"",
            "\"DLC_BBQChef_Head\"",
            "\"DLC_CosPlay_Chest\"",
            "\"DLC_CosPlay_Face\"",
            "\"DLC_CosPlay_Feet\"",
            "\"Combo_RemoteControlBucketDrill1\"",
            "\"DLC_CosPlay_Head\"",
            "\"AlternateOutfit\"",
            "\"UranusZoneShirtDispenser\"",
            "\"Combo_RemoteControlBucketDrill2\"",
            "\"TirFanOutfitDispenser\"",
            "\"FireCrackers\"",
            "\"Gems\"",
            "\"Combo_RemoteControlBucketDrill3\"",
            "\"PlayingCards\"",
            "\"CasinoChips\"",
            "\"BoxOfNails\"",
            "\"Combo_RemoteControlBucketDrill4\"",
            "\"GasolineCanister\"",
            "\"Grenade\"",
            "\"BoykinGrenade\"",
            "\"Magazine_Food_Healthy_Choices\"",
            "\"QueenBeeJar\"",
            "\"Dynamite\"",
            "\"SullivanFlare_PlayerVersion\"",
            "\"Magazine_Alcohol_Hangover_Cures\"",
            "\"StickyBomb\"",
            "\"BagofMarbles\"",
            "\"FireworkRockets\"",
            "\"AcetyleneTank\"",
            "\"Keg\"",
            "\"Dynameat\"",
            "\"FlashGrenade\"",
            "\"LiquidNitrogen\"",
            "\"RemoteMine\"",
            "\"Pegasus\"",
            "\"BouncingBeauty\"",
            "\"CryoPod\"",
            "\"WhippedCream\"",
            "\"Pizza\"",
            "\"Taco\"",
            "\"Burrito\"",
            "\"OnionRing\"",
            "\"Chili\"",
            "\"Sushi\"",
            "\"Magazine_PP_Survivor_Angel_Prince\"",
            "\"BBQChicken\"",
            "\"BBQRibs\"",
            "\"Pasta\"",
            "\"Magazine_Gambling_Luck_You\"",
            "\"BakedPotato\"",
            "\"Bacon\"",
            "\"Beans\"",
            "\"Magazine_PP_Weapon_Basic_Training_Monthly\"",
            "\"Snack\"",
            "\"Brownie\"",
            "\"Cookies\"",
            "\"Magazine_Item_Edged_Lone_Blade\"",
            "\"Pie\"",
            "\"Cake\"",
            "\"Donuts\"",
            "\"Mgz_Item_Construction_Jackhammer_Weekly\"",
            "\"Milk\"",
            "\"CoffeeCreamer\"",
            "\"LargeSoda\"",
            "\"Magazine_PP_Psycho_Dangerous_People_Weekly\"",
            "\"Coffee\"",
            "\"Wine\"",
            "\"Beer\"",
            "\"Magazine_Leadership_For_Losers\"",
            "\"NectarJuice\"",
            "\"QuickStepJuice\"",
            "\"RandomizerJuice\"",
            "\"SpitfireJuice\"",
            "\"UntouchableJuice\"",
            "\"ZombaitJuice\"",
            "\"PainKillerJuice\"",
            "\"Magazine_PP_Weapon_Armed_And_Awesome\"",
            "\"AppleMoney\"",
            "\"SpoiledBacon\"",
            "\"SpoiledBBQChicken\"",
            "\"Mgz_Item_Entertainment_Video_Game_Weekly\"",
            "\"SpoiledFish\"",
            "\"SpoiledLobster\"",
            "\"SpoiledHamburger\"",
            "\"Magazine_Item_Sports_Total_Sporting_Weekly\"",
            "\"SpoiledSteak\"",
            "\"SpoiledSushi\"",
            "\"Whiskey\"",
            "\"Magazine_Item_Furniture_Designer_For_Homes\"",
            "\"Pretzel\"",
            "\"Popcorn\"",
            "\"CottonCandy\"",
            "\"Magazine_Food_The_World_Chef\"",
            "\"SpaceSteak\"",
            "\"Flare\"",
            "\"Combo_PropaneTankNails\"",
            "\"Magazine_Juice_Top_Ten_Drink_Mixes\"",
            "\"Magazine_Gambling_Wealth\"",
            "\"Apple\"",
            "\"EnergizerJuice\"",
            "\"Magazine_Shotokan_Karate_Made_Easy\"",
            "\"Melon\"",
            "\"Jellybeans\"",
            "\"SpoiledHotDog\"",
            "\"Magazine_Item_Toy_Toyapalooza\"",
            "\"Fish\"",
            "\"SpoiledBBQRibs\"",
            "\"Magazine_Four_Wheel_Fun\"",
            "\"Mgz_Item_Entertainment_Video_Game_Weekly\"",
            "\"Fries\"",
            "\"Magazine_Stunt_Devils\"",
            "\"OneHundredDollars\"",
            "\"Magazine_Sports_To_The_Extreme\"",
            "\"Pineapple\"",
            "\"GamblingDollars\"",
            "\"OneThousandDollars\"",
            "\"Magazine_PP_Female_Survivor_Playboy\"",
            "\"IceCream\"",
            "\"FiveHundredDollars\"",
            "\"TenThousandDollars\"",
            "\"Magazine_Economy_Lords_Of_Cash\"",
            "\"OrangeJuice\"",
            "\"FiveThousandDollars\"",
            "\"HundredThousandDollars\"",
            "\"Magazine_Economy_Thrifty_Trader\"",
            "\"TwoThousandDollars\"",
            "\"Camera_Magazine_1\"",
            "\"Camera_Magazine_2\"",
            "\"Magazine_PP_Weapon_Fortune_Fighter\"",
            "\"Camera_Magazine_3\"",
            "\"VelvetRope\"",
            "\"LargeShoppingBoxes\"",
            "\"Magazine_PP_Zombie_Undead_Solutions\"",
            "\"PatioTable\"",
            "\"Bench_2\"",
            "\"PottedPlant_8\"",
            "\"Magazine_Gambling_Fortune_City_Riches\"",
            "\"Microscope\"",
            "\"CinderBlock\"",
            "\"Magazine_PP_Zombie_Spectral_Talkers\"",
            "\"PoolCue\"",
            "\"GarbageCan_1\"",
            "\"Barrel_Large\"",
            "\"MannequinMaleTorsoLLegRLeg\"",
            "\"HunkOfMeat\"",
            "\"NewspaperBox\"",
            "\"Crowbar\"",
            "\"SandwichBoard\"",
            "\"ProtesterSign\"",
            "\"LizardMask\"",
            "\"Football\"",
            "\"BowieKnife\"",
            "\"SpoolWire\"",
            "\"Generator\"",
            "\"Intestine\"",
            "\"Plate_Single\"",
            "\"Parasol\"",
            "\"GumballMachine\"",
            "\"PaintCan\"",
            "\"FunnyPainting\"",
            "\"PeaceArt\"",
            "\"Dumbbell\"",
            "\"MedicineBall\"",
            "\"SledgeHammer\"",
            "\"WaterBottle\"",
            "\"GiantStuffedDonkey\"",
            "\"WaterBottle_fromcooler\"",
            "\"GiantStuffedElephant\"",
            "\"Tomahawk\"",
            "\"ComputerCase\"",
            "\"Keyboard\"",
            "\"MusicDisc_Single\"",
            "\"MannequinFemaleRightArm\"",
            "\"MannequinFemaleLeftArm\"",
            "\"MannequinFemaleRightLeg\"",
            "\"MannequinFemaleLeftLeg\"",
            "\"MannequinFemaleHead\"",
            "\"MannequinFemaleHeadTorso\"",
            "\"Hanger\"",
            "\"MannequinFemaleWaistRLegRFoot\"",
            "\"MannequinFemaleLLegLFoot\"",
            "\"Mannequin_Female\"",
            "\"MannequinMaleRightLeg\"",
            "\"MannequinMaleLeftLeg\"",
            "\"MannequinMaleRightArm\"",
            "\"MannequinMaleLeftArm\"",
            "\"MannequinMaleHead\"",
            "\"Mannequin_Male\"",
            "\"Swordfish\"",
            "\"BoxingGloves\"",
            "\"VinylRecord_Single\"",
            "\"LawnDart\"",
            "\"SoccerBall\"",
            "\"Machete\"",
            "\"ConstructionHat\"",
            "\"Lamp\"",
            "\"MetalBarricade\"",
            "\"Spear\"",
            "\"GarbageCan_2\"",
            "\"Chair_1\"",
            "\"Chair_2\"",
            "\"Chair_3\"",
            "\"Painting3\"",
            "\"Painting2\"",
            "\"PottedPlant_1\"",
            "\"PottedPlant_2\"",
            "\"PottedPlant_3\"",
            "\"PottedPlant_4\"",
            "\"Mailbox\"",
            "\"PottedPlant_5\"",
            "\"PottedPlant_6\"",
            "\"CookingPot\"",
            "\"GarbageCan_3\"",
            "\"Chair_4\"",
            "\"NoveltyPokerChip\"",
            "\"FoamHand\"",
            "\"Vase2\"",
            "\"SquareSign\"",
            "\"Chair_5\"",
            "\"Chair_6\"",
            "\"Chair_7\"",
            "\"Chair_8\"",
            "\"RCHelicopter\"",
            "\"Bench\"",
            "\"LcdMonitor\"",
            "\"MoneyCase\"",
            "\"Shampoo\"",
            "\"TIR_chair\"",
            "\"MoneyCase_TK\"",
            "\"MoneyCase_Americana\"",
            "\"MoneyCase_SlotRanch\"",
            "\"MoneyCase_Yucatan\"",
            "\"MoneyCase_Atlantica\"",
            "\"MoneyCase_Protester\"",
            "\"MoneyCase_Helicopter\"",
            "\"MoneyCase_Scoops\"",
            "\"PottedPlant_7\"",
            "\"GiftShopLamp\"",
            "\"Chair_10\"",
            "\"Flashlight\"",
            "\"BingoBall\"",
            "\"Tikitorch\"",
            "\"NoveltyBottle\"",
            "\"AcousticGuitar\"",
            "\"WoodSwordAndShield\"",
            "\"NoveltyPerfume\"",
            "\"CardboardCutout\"",
            "\"GiantDice\"",
            "\"Particle_Board\"",
            "\"Amp\"",
            "\"HotelLamp\"",
            "\"BullSkull\"",
            "\"MMAGloves\"",
            "\"WrenchLarge\"",
            "\"Vase3\"",
            "\"Newspaper\"",
            "\"CarTire\"",
            "\"lwn_flower\"",
            "\"MinigameMooseHeadRed\"",
            "\"MinigameMooseHeadBlue\"",
            "\"MinigameMooseHeadGreen\"",
            "\"MinigameMooseHeadYellow\"",
            "\"MinigamePike\"",
            "\"StickIt_PonyOnStick\"",
            "\"stickin_painting\"",
            "\"stickit_ServbotMask\"",
            "\"Mayonnaise\"",
            "\"WheelchairTank\"",
            "\"GrassTrimmer\"",
            "\"WeedTendonizer\"",
            "\"AlienHead\"",
            "\"EscapePod\"",
            "\"GiantSpaceshipToy\"",
            "\"ToyRocketShip\"",
            "\"TIR_Sign\"",
            "\"TIRTwoByFour\"",
            "\"TIRStepLadder\"",
            "\"TIRPan\"",
            "\"MascotMask\"",
            "\"TIRBaseballBat\"",
            "\"SpaceBench\"",
            "\"Chair_Casino\"",
            "\"TIODPlywood1\"",
            "\"TIODPlywood2\"",
            "\"GreenHunkOfMeat\"",
            "\"BowlingPin\"",
            "\"BassGuitar\"",
            "\"ElectricGuitar\"",
            "\"BaseballBat\"",
            "\"BikeForks\"",
            "\"PitchFork\"",
            "\"CashRegister\"",
            "\"BroomHandle\"",
            "\"HandBag\"",
            "\"Suitcase\"",
            "\"RouletteWheel\"",
            "\"Broadsword\"",
            "\"MooseHead\"",
            "\"KCMooseHead\"",
            "\"MicStand\"",
            "\"PonyOnStick\"",
            "\"NightStick\"",
            "\"Pan\"",
            "\"Painting\"",
            "\"Battery\"",
            "\"LeafRake\"",
            "\"MeatCleaver\"",
            "\"BBQChef_MeatCleaver\"",
            "\"ChefKnife\"",
            "\"GiantStuffedBear\"",
            "\"GiantStuffedRabbit\"",
            "\"Paddle\"",
            "\"CookingOil\"",
            "\"MotorOil\"",
            "\"spar_dummy\"",
            "\"GasBarrel\"",
            "\"StepLadder\"",
            "\"AdBoard\"",
            "\"RopeLink\"",
            "\"ChainLink\"",
            "\"SpotLight\"",
            "\"Bust_Centurion\"",
            "\"RB_couch\"",
            "\"Vase\"",
            "\"FireworksBazooka\"",
            "\"FireworksBazooka_Bomber\"",
            "\"TennisRacket\"",
            "\"SGBallLauncherRed\"",
            "\"SGBallLauncherGreen\"",
            "\"SGBallLauncherYellow\"",
            "\"NineIron\"",
            "\"WheelChair\"",
            "\"Lawnmower\"",
            "\"WheelBarrow\"",
            "\"DrinkCart\"",
            "\"FlameThrower\""});
            this.clb_ItemList.Location = new System.Drawing.Point(-184, 342);
            this.clb_ItemList.Name = "clb_ItemList";
            this.clb_ItemList.Size = new System.Drawing.Size(311, 396);
            this.clb_ItemList.TabIndex = 0;
            this.clb_ItemList.SelectedIndexChanged += new System.EventHandler(this.checkedListBox1_SelectedIndexChanged);
            // 
            // tv_Items
            // 
            this.tv_Items.CheckBoxes = true;
            this.tv_Items.Location = new System.Drawing.Point(368, 98);
            this.tv_Items.Name = "tv_Items";
            treeNode1.Name = "Node6";
            treeNode1.Text = "Node6";
            treeNode2.Name = "Node7";
            treeNode2.Text = "Node7";
            treeNode3.Name = "Node8";
            treeNode3.Text = "Node8";
            treeNode4.Name = "Node0";
            treeNode4.Text = "Node0";
            treeNode5.Name = "Node9";
            treeNode5.Text = "Node9";
            treeNode6.Name = "Node10";
            treeNode6.Text = "Node10";
            treeNode7.Name = "Node11";
            treeNode7.Text = "Node11";
            treeNode8.Name = "Node1";
            treeNode8.Text = "Node1";
            treeNode9.Name = "Node12";
            treeNode9.Text = "Node12";
            treeNode10.Name = "Node13";
            treeNode10.Text = "Node13";
            treeNode11.Name = "Node14";
            treeNode11.Text = "Node14";
            treeNode12.Name = "Node2";
            treeNode12.Text = "Node2";
            treeNode13.Name = "Node17";
            treeNode13.Text = "Node17";
            treeNode14.Name = "Node3";
            treeNode14.Text = "Node3";
            treeNode15.Name = "Node15";
            treeNode15.Text = "Node15";
            treeNode16.Name = "Node16";
            treeNode16.Text = "Node16";
            treeNode17.Name = "Node4";
            treeNode17.Text = "Node4";
            treeNode18.Name = "Node5";
            treeNode18.Text = "Node5";
            this.tv_Items.Nodes.AddRange(new System.Windows.Forms.TreeNode[] {
            treeNode4,
            treeNode8,
            treeNode12,
            treeNode14,
            treeNode17,
            treeNode18});
            this.tv_Items.Size = new System.Drawing.Size(306, 374);
            this.tv_Items.TabIndex = 1;
            this.tv_Items.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.treeView1_AfterSelect);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(750, 534);
            this.Controls.Add(this.tv_Items);
            this.Controls.Add(this.clb_ItemList);
            this.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.Name = "Form1";
            this.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.Text = "DR2OTR Randomizer";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private CheckedListBox clb_ItemList;
        private TreeView tv_Items;
    }
}